from unittest.mock import patch

from medicare_synth.cli import main


def test_cli_scenario_subcommand():
    code = main(["scenario", "--name", "valid_baseline_cohort"])
    assert code == 0


def test_cli_validate_subcommand_success():
    code = main(["validate", "--scenario", "valid_baseline_cohort"])
    assert code == 0


def test_cli_validate_subcommand_failure():
    code = main(["validate", "--scenario", "invalid_orphaned_claim"])
    assert code == 1


def test_cli_manifest_subcommand_baseline():
    code = main(["manifest", "--type", "baseline"])
    assert code == 0


def test_cli_manifest_subcommand_evidence():
    code = main(["manifest", "--type", "evidence"])
    assert code == 0


def test_cli_validate_subcommand_output_dir(tmp_path):
    import json

    out_dir = tmp_path / "val_out"
    code = main(
        [
            "validate",
            "--scenario",
            "valid_baseline_cohort",
            "--output-dir",
            str(out_dir),
        ]
    )
    assert code == 0
    report_file = out_dir / "validation_report.json"
    assert report_file.exists()

    with open(report_file, "r", encoding="utf-8") as f:
        data = json.load(f)
    assert "findings" in data
    assert isinstance(data["findings"], list)


def test_cli_auto_workflow_dry_run():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_json_report(tmp_path):
    report_path = str(tmp_path / "report.json")
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--json-report", report_path])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=report_path,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_md_report(tmp_path):
    report_path = str(tmp_path / "report.md")
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--md-report", report_path])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=report_path,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_changelog_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--changelog-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=True,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_git_clean_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--git-clean-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=True,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_html_report(tmp_path):
    report_path = str(tmp_path / "report.html")
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--html-report", report_path])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=report_path,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_audit_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--audit-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=True,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_validation_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--validation-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=True,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_export_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--export-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=True,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_diff_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--diff-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=True,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_catalog_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--catalog-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=True,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_expansion_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--expansion-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=True,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_benchmark_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--benchmark-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=True,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_summary_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--summary-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=True,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_manifest_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--manifest-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=True,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_dag_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--dag-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=True,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_temporal_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--temporal-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=True,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_evidence_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--evidence-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=True,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_provenance_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--provenance-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=True,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_checkout_main():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--checkout-main"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=True,
            all_checks=False,
        )


def test_cli_auto_workflow_all_checks():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--all-checks"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=True,
        )


def test_cli_auto_workflow_accounting_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--accounting-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=True,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_uniqueness_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--uniqueness-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=True,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_orphan_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--orphan-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=True,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_privacy_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--privacy-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=True,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_mortality_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--mortality-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=True,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_enrollment_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--enrollment-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=True,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_dob_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--dob-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=True,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_provider_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--provider-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=True,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_icd_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--icd-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=True,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_hcpcs_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--hcpcs-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=True,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_ndc_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--ndc-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=True,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_drg_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--drg-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=True,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_taxonomy_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--taxonomy-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=True,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_pos_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--pos-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=True,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_rev_center_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--rev-center-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=True,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_demographic_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--demographic-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=True,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_mbsf_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--mbsf-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=True,
            inpatient_check=False,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_inpatient_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--inpatient-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=True,
            snf_check=False,
            checkout_main=False,
            all_checks=False,
        )


def test_cli_auto_workflow_snf_check():
    with patch("medicare_synth.cli.run_autonomous_workflow", return_value=0) as mock_wf:
        code = main(["auto-workflow", "--dry-run", "--snf-check"])
        assert code == 0
        mock_wf.assert_called_once_with(
            commit_msg="feat: implement autonomous workflow subcommand and reconcile docs",
            title="feat: implement autonomous workflow subcommand and reconcile docs",
            body="Automated PR created by the autonomous workflow engine. Reconciles docs and adds CLI auto-workflow subcommand.",
            dry_run=True,
            skip_merge=False,
            json_report_path=None,
            md_report_path=None,
            html_report_path=None,
            changelog_check=False,
            git_clean_check=False,
            audit_check=False,
            validation_check=False,
            export_check=False,
            diff_check=False,
            profile_check=False,
            catalog_check=False,
            expansion_check=False,
            provenance_check=False,
            benchmark_check=False,
            summary_check=False,
            manifest_check=False,
            dag_check=False,
            temporal_check=False,
            evidence_check=False,
            accounting_check=False,
            uniqueness_check=False,
            orphan_check=False,
            privacy_check=False,
            mortality_check=False,
            enrollment_check=False,
            dob_check=False,
            provider_check=False,
            icd_check=False,
            hcpcs_check=False,
            ndc_check=False,
            drg_check=False,
            taxonomy_check=False,
            pos_check=False,
            rev_center_check=False,
            demographic_check=False,
            mbsf_check=False,
            inpatient_check=False,
            snf_check=True,
            checkout_main=False,
            all_checks=False,
        )
